# Example Cloud Build to build frontend & backend and push to Artifact Registry
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/retail-frontend:$SHORT_SHA','./frontend']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/retail-backend:$SHORT_SHA','./backend']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/$PROJECT_ID/retail-frontend:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/$PROJECT_ID/retail-backend:$SHORT_SHA']
# Add kubectl/gcloud deploy steps as needed
images:
- 'gcr.io/$PROJECT_ID/retail-frontend:$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/retail-backend:$SHORT_SHA'
